Multiqc@0.1.0
icgc-argo-workflows/argo-qc-tools pull request #29
Opened 2022-06-10 15:00 UTC by lindaxiang

2022-06-13 09:42 UTC, abenjak requested changes
`Dockerfile`: replace `latest` with the actual version

The rest looks good :)

2022-06-13 13:42 UTC, lindaxiang commented
> `Dockerfile`: replace `latest` with the actual version
> 
> The rest looks good :)

Thanks @abenjak . Very good point. :-)

2022-06-13 14:40 UTC, abenjak approved these changes

2022-06-14 15:37 UTC, pruzanov approved these changes

2022-06-14 15:37 UTC, pruzanov commented on multiqc/README.md
> +Please update this with a brief introduction of the package.
This is a placeholder, is this intentional? Is there going to be some actual documentation here?

2022-06-14 16:59 UTC, lindaxiang commented on multiqc/README.md
> +Please update this with a brief introduction of the package.
Thanks @pruzanov . Glad you point this out and indeed we need to have good documentation. I will work on this.

2022-06-15 17:50 UTC, lindaxiang commented on multiqc/README.md
> +Please update this with a brief introduction of the package.
FYI @pruzanov,  I've updated the `README.md`.

2022-06-15 17:53 UTC, merged